### PR TITLE
Profile Page

### PR DESCRIPTION
**Pull request by georgevmlambton**
Added profile page with input to update user's name

### CODE REVIEW

**Comment by PiyumikaBandula** [comment]
It is amazing. I get one error when loading it. 
Incorrect use of for attribute of FORM_ELEMENT.

It  suggests to refer to form fields by their id attribute.

**Comment by PiyumikaBandula** [comment]
It is perfectly runnning

**Review by PiyumikaBandula — APPROVED** [review]
After I installed @types/cors it is amazingly running. It improves the type checking right?

**Comment by georgevmlambton** [comment]
> After I installed @types/cors it is amazingly running. It improves the type checking right?

Yeah it's for typescript support

**Pull request merged**
